### ISSUE TITLE
这个是什么原因

### ISSUE THREAD

**Issue by sinperfor** [hwangzhun/file-translation-and-renaming-tool#1]
![Uploading 屏幕截图 2024-12-17 204345.png…]()

**Comment by sinperfor** [comment]
Traceback (most recent call last):
  File "main.py", line 213, in <module>
  File "tkinter\__init__.py", line 2071, in wm_iconbitmap
_tkinter.TclError: bitmap "C:/Users/huang/Desktop/GitHub/file-translation-and-renaming-tool/my_icon.ico" not defined

**Comment by hwangzhun** [comment]
应该之前把 icon 路径写死的问题，我稍后修复下这个问题

**Comment by hwangzhun** [comment]
> Traceback (most recent call last): File "main.py", line 213, in File "tkinter__init__.py", line 2071, in wm_iconbitmap _tkinter.TclError: bitmap "C:/Users/huang/Desktop/GitHub/file-translation-and-renaming-tool/my_icon.ico" not defined

已修复，请到 [Releases](https://github.com/hwangzhun/file-translation-and-renaming-tool/releases/tag/v1.0.2) 下载最新版本

**Comment by sinperfor** [comment]
好的，非常感谢
